### ISSUE TITLE
Mistakes in Romanian package

### ISSUE THREAD

**Issue by mafsi** [latex3/babel#117]
Please change the following lines:

https://github.com/latex3/babel/blob/ab490d0d5b59cf3e2354a81c09025be397cfa9a7/locale/ro/babel-ro.ini#L41
https://github.com/latex3/babel/blob/ab490d0d5b59cf3e2354a81c09025be397cfa9a7/locale/ro/babel-ro.ini#L64

**into**

`index = Index`

Index & Glossary are not the same in Romanian language.

## According to Romanian dictionary:

1. ***Index*** = Alphabetical or subject list placed at the end or beginning of a book or published in a separate volume, containing the subjects, authors or words contained therein, indicating the pages (and volumes) where they are located; index
2. **_Glossary_** = List of words accompanied by their explanation, conceived as an appendix or as an independent paper. 2. (inv.) Dictionary, vocabulary. 

----
Please see MWE
----

```latex
% !TeX program = pdflatex
% !TeX encoding = UTF-8
\documentclass{article}
\usepackage[romanian]{babel}
\usepackage{makeidx}
\makeindex
\usepackage[automake,sort=def]{glossaries-extra}
\makeglossaries
\newacronym{decont}{Decontare}{Justificare amănunțită, pe bază de 
acte, a folosirii unei sume (primite); (concr.) document, formular cu 
ajutorul căruia se face justificarea unor cheltuieli. – Din fr. 
décompte.} 
\newacronym{bilet}{Bilet}{Bucată mică de hârtie sau de carton 
imprimat care dă dreptul la intrarea (și ocuparea unui loc) într-o 
sală de spectacol, într-o arenă sportivă etc.} 

\begin{document}

Elevii\index{elevii} au reclamat de mai multe ori că transportul 
gratuit promis de către Guvern, nu este asigurat pe tot teritoriul 
țării și că din cauza lipsei procedurilor clare de 
decontare\index{decontare} a biletelor\index{decontare!bilete} de către 
operatorii privați, transportatorii refuză să ia elevi cu mașina și 
să le asigure gratuitatea, conform legii. 

\printindex
\printglossaries
\gls{decont} \gls{bilet}
\end{document}

```

**Comment by jbezos** [comment]
Thank you. Fixed in GitHub. It should be available in CTAN soon.

**Comment by mafsi** [comment]
@jbezos I updated Babel, but running the above MWE is still showing me Glosar instead of Index. (MiKTeX, Windows 10)
Shouldn't  be also updated this one?  https://ctan.org/tex-archive/macros/latex/contrib/babel-contrib/romanian
(I'm not a programmer...)

**Comment by jbezos** [comment]
Sorry, I thought the error was only in the `ini` files. I'm not sure if the `ldf` for Romanian is actively maintained. I've reopened the issue.

**Comment by jbezos** [comment]
Fixed also in the `ldf` file, now in CTAN.
